[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#todo: to target a specific solidity compiler, let's say 0.8.17
#solc_version ="0.8.17"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
